server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/BARBOSA191919/Microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service